### ISSUE TITLE
Sequencing Quality Control Standards

### ISSUE THREAD

**Issue by WangJian99** [griffithlab/neoag_vaccine_scripts#7]
I am very interested in these standards listed in the file fda_quality_thresholds.csv. However, I have been unable to locate a specific source or reference for these standards. Were these standards developed based on your lab's extensive experience with sequencing data? Or, are they referenced from a particular set of guidelines or a specific paper?

**Comment by evelyn-schmidt** [comment]
Hello @WangJian99!

Yes these thresholds were set based on the Griffith Lab's experience with sequencing data. The FDA does not have official thresholds. Our thresholds are relatively stringent so the data that falls below them is usually still useable but will be noted when we do our evaluation of the called candidates. 

We look more extensively at and have more levels then pass and failed for our basic data QC's (pulled in script [get_neoantigen_qc.py](https://github.com/griffithlab/neoag_vaccine_scripts/blob/master/scripts/get_neoantigen_qc.py)). For example:

- Total number of uniquly mapping reads generated for Tumor/Normal exome and Tumor RNA-seq (i.e. not counting duplicates that arise from PCR amplification of the same source DNA fragment.
    - <40,000,000 is poor
    - 40,000,000 - 50,000,000 is acceptable
    - 50,000,000 - 100,000,000 is good
    - \> 100,000,000 is excellent
- Duplication rates for tumor/normal DNA samples
    - \>75% is very poor
    - 50-75% is poor
    - 30-50% is acceptable
    - 20-30% is good
    - <20% is excellent
- Somalier results for tumor/normal sample relatedness
    - \>97.5% is excellent
    - 95-97.5% is good
    - 90-95% is concerning 
    - <90% is very concerning 
- "FREEMIX" results for contamination of both tumor and normal samples
    - <0.025 is good
    - 0.025-0.05 is concerning 
    - \>0.05 is very concerning 
 - RNA-seq metrics for % reads aligning to transcripts
    - \>90% is excellent
    - 75-90% is good
    - 50-75% is acceptable 
    - <50% is sub-optimal 

@susannasiebert and @malachig  might want to add some further clarification.

**Comment by WangJian99** [comment]
Hi @evelyn-schmidt ! Thank you for your detailed explanation, I understand now.
